-- MySQL Script generated by MySQL Workbench
-- Fri Jan 23 14:28:04 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema people
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `people` ;

-- -----------------------------------------------------
-- Schema people
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `people` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `people` ;

-- -----------------------------------------------------
-- Table `people`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `people`.`people` ;

CREATE TABLE IF NOT EXISTS `people`.`people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `from` DATETIME NULL,
  `to` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------------------------
-- Records of people
-- ----------------------------
INSERT INTO `people` VALUES ('1', 'Hanna', 'Velazquez', '2014-09-23 12:19:25', '2014-11-20 12:19:32');
INSERT INTO `people` VALUES ('2', 'Peter', 'Frampton', '2014-11-09 12:11:46', '2014-12-18 12:11:34');
INSERT INTO `people` VALUES ('3', 'Steve', 'Carey', '2014-09-15 12:12:25', '2014-12-28 12:12:33');
INSERT INTO `people` VALUES ('4', 'Ron', 'Lumis', '2014-08-18 12:12:54', '2014-11-12 12:13:04');
INSERT INTO `people` VALUES ('5', 'Hugh', 'Motcrief', '2014-08-12 12:13:29', '2014-12-24 12:13:37');
INSERT INTO `people` VALUES ('6', 'Bob', 'Renter', '2014-09-15 12:13:59', '2014-12-15 12:14:06');
INSERT INTO `people` VALUES ('7', 'Janet', 'Lemur', '2014-11-10 12:14:37', '2014-12-17 12:14:45');
INSERT INTO `people` VALUES ('8', 'George', 'Barret', '2014-09-15 12:15:08', '2014-11-19 12:15:15');
INSERT INTO `people` VALUES ('9', 'Leyla', 'Korg', '2014-09-14 12:15:38', '2014-10-24 12:15:47');
INSERT INTO `people` VALUES ('10', 'John', 'Morris', '2014-09-15 12:16:23', '2014-12-23 12:16:29');
INSERT INTO `people` VALUES ('11', 'Robert', 'Palmer', '2014-10-01 12:11:07', '2014-12-15 12:11:19');